[package]
name = "hello-wgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.30.5"
env_logger = "0.11.5"
log = "0.4.22"
wgpu = "22.1.0"
tokio = { version = "1.40.0", features = ["full"] }
bytemuck = { version = "1.19.0", features = [ "derive" ] }